development:
  adapter: postgresql
  encoding: utf8
  database: college_collage_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: college_collage_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: college_collage_production
  pool: 5
  username: 
  password: